[package]
name = "frei0r-macros"
version = "0.1.3"
edition = "2021"
license = "MIT"
repository = "https://github.com/kenkinming2002/frei0r-rs"
description = "Macros crate for frei0r-rs"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
